name : Internal file validations
on :
  workflow_dispatch :
jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.loglevel }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo "chandra"
