name: Testing ID
on:
  workflow_dispatch:
    inputs:
      Deploy-to:
        type: environment
        description: Select the environment
        required: true
      BuildID1:
        description: "Please Select the Build to be deployed"
        type: choice
        options:
        - build1
        - build2
        - build3

jobs:
  myJob:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.myInput1 != '' }}
    steps:
    - name: Print inputs
      run: |
        echo ${{ inputs.myInput1 }}
    
