name: Testing ID
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      myInput1:
        description: An input string
        type: string
        required: true
      myInput2:
        description: An input string
        type: string
        required: true
      myInput3:
        description: An input string
        type: string
        required: true

jobs:
  myJob:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.myInput != '' }}
    steps:
    - name: Print inputs
      run: |
        echo ${{ inputs.myInput }}
    
