name: Testing ID
on:
  workflow_dispatch:
    inputs:
      myInput:
        description: An input string
        type: string
        required: true

jobs:
  myJob:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.myInput != '' }}
    steps:
    - name: Print inputs
      run: |
        echo ${{ inputs.myInput }}
    
