name: Testing ID
on:
  workflow_dispatch:
    inputs:
      Deploy-to:
        type: environment
        description: Select the environment
        required: true
      BuildID1:
        description: "Please Enter the  Build Number to be deployed"
        type: string
        required: true 
      BuildID2:
        description: "Please Enter the  Build Number to be deployed"
        type: string
        required: true	  
      BuildID3:
        description: "Please Enter the  Build Number to be deployed"
        type: string
        required: true
jobs:
  myJob:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.myInput1 != '' }}
    steps:
    - name: Print inputs
      run: |
        echo ${{ inputs.myInput1 }}
    
