name : input validations
on :
  workflow_dispatch :
    inputs:      
      CMValue:
        type: boolean
        description: "is CM Server deploy requried?,select checkobx if required"
        default: true
      CDValue:
        type: boolean
        description: "is CD Server deploy requried?,select checkobx if required"
        default: false
jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.loglevel }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.loglevel }}
        
  print-tag-CM:
    if: ${{ github.event.inputs.CMValue == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - name: Print the input tag to STDOUT
      run: echo  The tags are ${{ inputs.loglevel }}
        
  print-tag-CD:
    if: ${{ github.event.inputs.CDValue == 'true' }}
    runs-on: ubuntu-latest 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.loglevel }}
    
