name : input validations
on :
  workflow_dispatch :
    inputs:      
      CMValue:
        type: boolean
        description: "is CM Server deploy requried?,do select if required"
      
      CDValue:
        type: boolean
        description: "is CD Server deploy requried?,do select if required"
        
jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.loglevel }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.loglevel }} 
