name : input validations
on :
  workflow_dispatch :
    inputs:
      logLevel:
        description: "Log level"
        required : True
        
      CMValue:
        type: boolean
        description: "is CM Server deploy requried?,do select if required"
        required : True
jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.loglevel }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.loglevel }} 
